### ISSUE TITLE
When respecting gitignore, pattern negated in gitignore should take over wildcard.

### ISSUE THREAD

**Issue by atplacasse** [moshfeu/vscode-compare-folders#126]
With `"compareFolders.respectGitIgnore": true`
Given this .gitgnore:
```
a*
!a1.txt
```
then file a1.txt should not be ignored.

See https://github.com/moshfeu/vscode-compare-folders/pull/97 for previous discussion.

**Comment by gliviu** [comment]
The `includeFilter` and `excludeFilter` provided by dir-compare work in a similar way to .gitignore but do not follow all the rules. Especially for whitelisting with `!`.

If we want to support all gitignore features we need to use a dedicated filtering package as [ignore](https://www.npmjs.com/package/ignore) which follows the [specs](https://git-scm.com/docs/gitignore).

I think our best option here is to provide some kind of extension to dir-compare that uses `ignore` instead of minimatch.

I will think about it and let you know.

**Comment by moshfeu** [comment]
@gliviu thanks! 
For now, [I cut off lines that start with `!`](https://github.com/moshfeu/vscode-compare-folders/blob/ecdb0d2b8048763a2bd9b73deed9bd32e83ba41e/src/services/gitignoreParser.ts#L21) to `includeFilter`. It works in some cases but not in the others. 

Working
```
src
!src/file.ts
```

Not working

```
a*
!a1.txt
```

Maybe it's something specific with `*` in end of line?

**Comment by gliviu** [comment]
I will look into it. 
Meanwhile I am progressing with gitignore solution [supported by dir-compare](https://github.com/gliviu/dir-compare/tree/feature/respect-gitignore/test/gitignoreSupport).

**Comment by moshfeu** [comment]
Thanks!

**Comment by gliviu** [comment]
> For now, I cut off lines that start with ! to includeFilter. It works in some cases but not in the others.
Moved this problem in #127 127

**Comment by gliviu** [comment]
Released new version with support for custom [glob filter](https://github.com/gliviu/dir-compare#glob-filter).
Example of .gitignore filter can be found in the docs: https://github.com/gliviu/dir-compare#implement-gitignore-filter.

**Comment by moshfeu** [comment]
@gliviu I've made a PR and I'd really appreciate your feedback 🙏

**Comment by gliviu** [comment]
I'll take a look later today and let you know.

**Comment by gliviu** [comment]
Left one minor comment. Looks good so far.
