### ISSUE TITLE
List compared folders in settings

### ISSUE THREAD

**Issue by llgcode** [moshfeu/vscode-compare-folders#18]
I always compared same folders, it could be useful to set a list of folders in settings so we can pickup when needed.

**Comment by RodAtBurkeDataConsulting** [comment]
Could this be done by having a workspace with just the two folders in it (the ones you always want to compare) rather than having the folders in the extension settings? Then a mod to the extension could allow comparison (or a command/hotkey) of two selected folders, or even two folders if there are just two, without having to select them?

**Comment by llgcode** [comment]
I don't use workspace, I always open 1 folder at a time. 
But it seems to be an interesting option, what do you think @moshfeu ?

**Comment by moshfeu** [comment]
Agreed. Indeed a reasonable use case.
I hope I have have time to work an more flexible ways to choose folders. This is one of them.
