### ISSUE TITLE
it does not work, error message: "Cannot read property [0] of undefined"

### ISSUE THREAD

**Issue by Zvika88** [moshfeu/vscode-compare-folders#32]
I wish it was functional because such a feature is badly needed in Code. Yet when I compare projects I get a javascript error as per the title.

**Comment by moshfeu** [comment]
Thanks for report. It's clearly working for some people :)
Can you describe the steps that leads to the error. Also, can you include your system information?
You can copy it from the about menu. It should be something like:

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by Zvika88** [comment]
Hi Mosh, sorry for the late response, I am on a rush deadline and switched to my other editor (IntelliJ) for its compare feature, and was buried in work for a while... Anyhow, I tried again and now it is working! The JS error no longer shows up.

Strange but I am delighted. I see that you pushed an update 7 days ago - might it have fixed this?  Hard to know because I was not able to isolate the bug when it happened. The bug just showed up when I selected a folder, but it no longer does.

My project is way too big for IntelliJ, which chokes on its indexing - a problem that MS-Code does not have, even with ~1 million lines of code in a few thousand files. So I am thrilled to finally have a working "folders compare" that works with Code. Thank you so much for an awesome job!

So everything is good, I am ready to close the issue if that is OK with you.

Quick suggestion: IntelliJ has two cool features very useful in comparison: (a) where you can simply copy an entire file over to the other side with one click, which is useful if there are many changes but you are the only one working on a module so you just want to accept them all, and (b) where you copy from one side to the other with one click (instead of copy / paste from side to side. 

Both are great time savers. Would you consider adding these to CompareFolders?

Thanks again for a great job.
Zvika

**Comment by moshfeu** [comment]
I'm glad to hear :)
That's why I like vscode. It's much less "heavy" than the alternatives. You can close the issue.
(Also star the project and 5 stars the extension are very appreciated 😉)

About the suggestion. First, thanks! If I understand you correctly, you're talking about the diff view itself (the view after you click on a file with differences).
Unfortunately, vscode lacks that very important feature (https://github.com/microsoft/vscode/issues/25887). I made another extension to add this capability. It's not perfect. vscode lacks also important APIs to make it better but I improve it from time to time as much as I can.
I have a thought to integrate both of the extensions so "compareFolders" will offer to compare files using "Diff & Merge" but haven't get to it yet.
Please try "Diff & Merge" and if it fits to your needs, create an issue to integrate it with "compareFolders" and I hope vscode's API will allow me to do this.

**Comment by Zvika88** [comment]
will do!
