### ISSUE TITLE
integrate with "Diff & Merge"

### ISSUE THREAD

**Issue by Zvika88** [moshfeu/vscode-compare-folders#34]
(From "Diff & Merge" but should be the visa-versa)
> This is a great extension, but it only works on a single file. It would have been very useful if the feature could have been called from within a folder compare function such as the author's awesome Compare Folder extension, to allow integration of entire project trees without having to invoke the command over and over again (possibly hundreds of times...). 

The reasonable use pattern would be to run Compare Folders, then go over the diffs, and have the diff-merge extension automatically available and operational within the extension's toolbar on every file being reviewed from the diff list.

**Comment by moshfeu** [comment]
I've started the implementation. Hopefully it will be in the next release (0.12.0).

Meanwhile, I'd be happy if you can test it. You can download it from [here](https://github.com/moshfeu/vscode-compare-folders/releases/download/v0.12.0/compare-folders-0.12.0.vsix).

This option is off by default. In order to enable the integration, search for `compareFolders.useDiffMerge` in the settings page.

**Comment by moshfeu** [comment]
@Zvika88 ☝️
