### ISSUE TITLE
Feature request: ability to use this for git difftool and mergetool

### ISSUE THREAD

**Issue by shovaen** [moshfeu/vscode-compare-folders#38]
If there is a command line argument that can be given to vscode to allow this to be used when passing -d to git difftool that would be awesome.

**Comment by moshfeu** [comment]
The only way I see, the command will looks like

```shell
COMPARE_FOLDERS=DIFF code ~/Desktop/compareable/folder1 ~/Desktop/compareable/folder2
```

And it will open a vscode instance with a workspace with the 2 of the folders and right await it will focus compareFolders tabs and show the diffs.

Is this sounds a good (or enough) experience for you?

**Comment by shovaen** [comment]
Experience-wise yes. See these docs for the format that is passed in to code from git:

https://code.visualstudio.com/docs/editor/versioncontrol#_vs-code-as-git-editor

Great plug-in by the way. At first I tried this with just right-clicking on the left and right folders to compare them, but for some reason the context menu option wasn't there. If it can be automatic from the command line that is best of course.

**Comment by shovaen** [comment]
Also thanks for the quick reply! :)

**Comment by moshfeu** [comment]
Thanks for your warm words :)
Ok. I'll add it in the next release.
I wander why the context menu wasn't appear. This functionality added in v0.10.0, did you tried on an older version?

**Comment by shovaen** [comment]
I have just started using it as of last week. You might use that config setup I linked and command line "git difftool -d" as a test case.

**Comment by moshfeu** [comment]
I'll try. But if you start in a regular way e.g. open vscode and then open a folder and select 2 folders. Can you see the context menu?

**Comment by shovaen** [comment]
From explorer? No looks like it doesn't show up. Only way I've used it successfully is by using the open two folders command.

![image](https://user-images.githubusercontent.com/11812295/84554780-19472980-acdf-11ea-90e4-7bc1593dc21d.png)

Let me know if there are logs or other things I can provide.

**Comment by moshfeu** [comment]
If I'm not mistaking, seems like you chose only 1 folder. In order to see that menu, you should choose 2 (using <kbd>ctrl</kbd> or <kbd>cmd</kbd>)

<img width="462" alt="Screen Shot 2020-06-13 at 22 41 17" src="https://user-images.githubusercontent.com/3723951/84577660-0b6cd380-adc7-11ea-9d9f-c59f32db2a04.png">

**Comment by moshfeu** [comment]
I've pre-released v0.13.0. I'd love to get your feedback (please try to use in the right way (e.g. 2 folders) but also in wrong ways).

https://github.com/moshfeu/vscode-compare-folders/releases/download/v0.13.0/compare-folders-0.13.0.vsix

Thanks!

**Comment by moshfeu** [comment]
About `git difftool -d`. I wasn't aware about this feature in vscode. From what I understand, when you run it with 2 branches, vscode is opened with the diffs in the Explorer tab. Is there anything the extension can does better?

**Comment by cipri-tom** [comment]
Awesome feature ! It works !! (with `git difftool -d`)

One possible improvement is to use the folder names instead of "My folder" and "Compared folder", because in git it is not always clear which one is "mine" (depends if I to `git dtd master feature/branch` or `git dtd feature/branch master`). (`dtd` is a git alias that I've setup for `difftool -d`).

This is just because you asked, but it is already awesome the way it is.

Another potential nice-to-have would be to open with an overview of the two folders, in light of some familiarity from other tools. Here's how it looks in Meld:

![Screenshot 2020-11-23 at 22 37 20](https://user-images.githubusercontent.com/2991890/100018744-367b3a80-2ddd-11eb-8bd0-546b007edbdd.png)

**Comment by moshfeu** [comment]
Thanks @cipri-tom . Sadly, I don't think it's possible to change the sections' titles.
That's why the extension shows the path below it

![Screen Shot 2020-11-25 at 18 11 20](https://user-images.githubusercontent.com/3723951/100253500-dd7ce500-2f49-11eb-9f4d-103c739b0bd0.png)

I thought about present it as Meld but I wanted to keep it in the sidebar so it will still be available even when the editor is open. (and vscode doesn't open views in new windows but only in the main window).
I'd love to continue to discuss it with you if needed. Please create another issue to not mixing ideas. Thanks :)
