### ISSUE TITLE
Please change the activation (in package.json) from onload - '*' to onCommand<xyz>

### ISSUE THREAD

**Issue by rbadapanda** [moshfeu/vscode-compare-folders#53]
Instead of loading it when vscode starts, probably it will be better to activate it on the following commands:

foldersCompare.refresh
foldersCompare.chooseFoldersAndCompare
foldersCompare.compareFoldersAgainstWorkspace
foldersCompare.compareSelectedFolders
foldersCompare.copyToCompared
foldersCompare.copyToMy
foldersCompare.takeMyFile
foldersCompare.takeComparedFile
foldersCompare.deleteFile

**Comment by moshfeu** [comment]
Thanks for the suggestion.
[ASAIK](https://medium.com/@moshfeu/he-activity-comparefolders-a-visual-studio-code-extension-journey-part-ii-77e0467a12f6?source=friends_link&sk=34deefe0a5a41ce97c6197a5f2813e0f), the extension must be activated at start in order to show the icon in the Activity Bar. Do you know another way to do it?
